export const siteConfig = {
  name: "HomeScope",
  author: "Mahmoud Amr",
  jobTitle: "Senior Staff Engineer",
  location: "Cairo, Egypt",
  email: "contact@mahmoudamr.dev",
  url: "https://homescope.mahmoudamr.dev",
  tagline: "Interactive US housing-market explorer — state to ZIP, instant metric switching.",
  // Marketing one-liner used on the case-study page hero.
  pitch:
    "A production-grade geospatial data product: real Census geometry, a drift-resilient ETL, and 33k+ regions that recolor instantly. Built end to end by Mahmoud Amr.",
  description:
    "Explore US home prices, inventory, and market trends across state, metro, county, and ZIP on an interactive map. A geospatial data-product showcase by Mahmoud Amr, Senior Staff Engineer.",
  availableForWork: true,
  github: "https://github.com/mahmoudamr512",
  linkedin: "https://www.linkedin.com/in/mahmoud-a-46818913b/",
  upwork: "https://www.upwork.com/freelancers/mahmouda299",
  repo: "https://github.com/mahmoudamr512/homescope",
  // Author photo path (bundled in /public); falls back to initials if unset.
  photo: process.env.NEXT_PUBLIC_AUTHOR_PHOTO ?? "/mahmoud-amr.jpg",
  initials: "MA",
  portfolio: [
    { label: "Portfolio — mahmoudamr.dev", href: "https://mahmoudamr.dev" },
    { label: "FastNet", href: "https://fastnet.mahmoudamr.dev" },
    { label: "obvote.com", href: "https://obvote.com" },
    { label: "GitHub", href: "https://github.com/mahmoudamr512" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/mahmoud-a-46818913b/" },
    { label: "Upwork", href: "https://www.upwork.com/freelancers/mahmouda299" },
  ],
  // Recruiter/client-facing skills (also feeds Person.knowsAbout for SEO).
  skills: [
    "Geospatial visualization (MapLibre / Mapbox GL)",
    "Vector tiles & PMTiles",
    "PostGIS & spatial data modeling",
    "Data engineering & resilient ETL",
    "Next.js / React / TypeScript",
    "Python",
    "System design & performance",
    "AI-native applications",
  ],
  keywords: [
    "Mahmoud Amr",
    "Mahmoud Amr Senior Staff Engineer",
    "Mahmoud Amr software engineer",
    "geospatial visualization",
    "MapLibre",
    "PMTiles",
    "PostGIS",
    "Next.js",
    "data engineering",
    "ETL",
    "housing market data",
    "choropleth map",
    "software engineer portfolio",
    "Cairo software engineer",
    "hire software engineer",
  ],
} as const;
